import { createClient } from "@supabase/supabase-js";

export const config = {
    runtime: "edge",
};

export default async function handler(request: Request) {
    const url = new URL(request.url);
    const noteId = url.pathname.split("/").pop(); // usually /note/ID here

    // We load standard env vars (Vercel exposes these automatically if set up in dashboard)
    const supabaseUrl = process.env.VITE_SUPABASE_URL || "";
    const supabaseKey = process.env.VITE_SUPABASE_ANON_KEY || "";

    let noteTitle = "Om's Workspace Note";
    let noteDesc = "Shared note from Om Narkhede's Workspace.";
    let authorName = "Om Narkhede";

    if (noteId && supabaseUrl && supabaseKey) {
        const supabase = createClient(supabaseUrl, supabaseKey);
        const { data } = await supabase
            .from("notes")
            .select("title, content, author_name")
            .eq("id", noteId)
            .single();

        if (data) {
            if (data.title) noteTitle = data.title;
            if (data.author_name) authorName = data.author_name;
            if (data.content) {
                // Strip HTML and take first 150 chars for description
                noteDesc = data.content.replace(/<[^>]+>/g, "").substring(0, 150).trim() + "...";
            }
        }
    }

    // The base HTML that Vercel serves for index.html
    // Here we explicitly insert OG tags and Title and return it
    const html = `
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>${noteTitle}</title>
        
        <!-- Social Media Meta Tags explicitly generated by Edge server -->
        <meta property="og:title" content="${noteTitle}" />
        <meta property="og:description" content="${noteDesc}" />
        <meta property="og:type" content="article" />
        <meta property="og:site_name" content="${authorName}'s Workspace" />
        <meta name="twitter:card" content="summary" />
        <meta name="twitter:title" content="${noteTitle}" />
        <meta name="twitter:description" content="${noteDesc}" />
        <meta name="author" content="${authorName}" />
        
        <meta http-equiv="refresh" content="0; url=/#/note/${noteId}" />
      </head>
      <body>
        <p>Redirecting to Note...</p>
        <script>
            window.location.href = "/#/note/${noteId}";
        </script>
      </body>
    </html>
  `.trim();

    return new Response(html, {
        status: 200,
        headers: {
            "Content-Type": "text/html; charset=utf-8",
            "Cache-Control": "public, max-age=60, s-maxage=3600", // Cache effectively in Vercel edge
        },
    });
}
